package ir.doint.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BopInfoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBopInfoAllPropertiesEquals(BopInfo expected, BopInfo actual) {
        assertBopInfoAutoGeneratedPropertiesEquals(expected, actual);
        assertBopInfoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBopInfoAllUpdatablePropertiesEquals(BopInfo expected, BopInfo actual) {
        assertBopInfoUpdatableFieldsEquals(expected, actual);
        assertBopInfoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBopInfoAutoGeneratedPropertiesEquals(BopInfo expected, BopInfo actual) {
        assertThat(expected)
            .as("Verify BopInfo auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBopInfoUpdatableFieldsEquals(BopInfo expected, BopInfo actual) {}

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBopInfoUpdatableRelationshipsEquals(BopInfo expected, BopInfo actual) {}
}
